Repository dikhan/terraform-provider-openapi, pull requests merged in 2019-12, with the labels that each got.

#191 [bug-fix] Do not fail when schema property configuration (defined in openapi config file) command exec fails or source file to get default value from does not exists
  docs/plugin_configuration_schema.md
  go.mod
  go.sum
  openapi/plugin_config_services_schema_property_configuration.go
  openapi/plugin_config_services_schema_property_configuration_test.go
  openapi/plugin_config_services_stub.go
  openapi/provider_factory.go
  openapi/provider_factory_test.go
  tests/integration/provider_plugin_configuration_test.go
Labels: bug-fix

#193 Validate missing header values or security definition values before making API call
  go.mod
  go.sum
  openapi/openapi_client.go
  openapi/openapi_client_test.go
  openapi/openapi_spec_authenticator_api.go
  openapi/openapi_spec_authenticator_api_test.go
  openapi/openapi_spec_authenticator_apikey.go
  openapi/openapi_spec_authenticator_apikey_header.go
  openapi/openapi_spec_authenticator_apikey_header_test.go
  openapi/openapi_spec_authenticator_apikey_query.go
  openapi/openapi_spec_authenticator_apikey_query_test.go
  openapi/openapi_spec_authenticator_apikey_test.go
  openapi/openapi_spec_authenticator_refresh_token.go
  openapi/openapi_spec_authenticator_refresh_token_test.go
  openapi/openapi_spec_header.go
  openapi/openapi_v2_headers.go
  openapi/openapi_v2_headers_test.go
  openapi/provider_configuration.go
  openapi/provider_configuration_test.go
  tests/e2e/resources_test.go
Labels: enhancement, feature request

#195 Fix gorelease warnings
  .goreleaser.yml
Labels: enhancement, tech-debt

#196 Bump up version to 0.24.0
  version
Labels: new version

#198 [FeatureRequest: Issue #197] Automate release deployments
  .travis.yml
  Makefile
  go.mod
  go.sum
  scripts/release_notes.sh
  scripts/semver.sh
Labels: feature request

#199 [FeatureRequest: Issue #198] Updating release documentation
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .travis.yml
  Makefile
  docs/release.md
  go.mod
  go.sum
  scripts/release_notes.sh
Labels: feature request

#200 [NewRelease] v0.25.0
  version
Labels: new version

#201 [NewRelease] v0.25.0
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
Labels: new version

#202 [NewRelease] v0.25.0
  Makefile
  go.sum
Labels: new version

#203 [NewRelease] v0.25.0
  .travis.yml
  Makefile
Labels: new version

#205 [FeatureRequest: Issue #204] Provide telemetry in OpenAPI Terraform Provider
  docs/plugin_configuration_schema.md
  go.mod
  go.sum
  openapi/plugin_config.go
  openapi/plugin_config_schema.go
  openapi/plugin_config_schema_test.go
  openapi/plugin_config_telemetry.go
  openapi/plugin_config_telemetry_handler.go
  openapi/plugin_config_telemetry_handler_test.go
  openapi/plugin_config_telemetry_provider_stub.go
  openapi/plugin_config_telemetry_test.go
  openapi/plugin_config_test.go
Labels: feature request

#206 [NewRelease] v0.26.0
  version
Labels: new version
