Repository dikhan/terraform-provider-openapi, pull requests merged in 2019-10, with the labels that each got.

#155 Feature/data source instance
  docs/how_to.md
  go.mod
  go.sum
  openapi/data_source_instance_factory.go
  openapi/data_source_instance_factory_test.go
  openapi/openapi_spec_resource_schema_definition.go
  openapi/openapi_spec_resource_schema_definition_test.go
  openapi/provider_factory.go
  openapi/provider_factory_test.go
  openapi/provider_test.go
  tests/e2e/gray_box_cdns_test.go
Labels: feature request

#158 fetch version from github instead of relying on local dir
  scripts/install.sh
Labels: bug

#162 Various hot bug fixes
  Makefile
  docs/how_to.md
  go.mod
  go.sum
  openapi/openapi_client_stub.go
  openapi/openapi_spec_resource_schema_definition_property.go
  openapi/resource_factory.go
  openapi/resource_factory_test.go
  openapi/test_utils.go
  tests/integration/resource_cdns_test.go
Labels: bug

#163 Feature/refresh token authenticator
  docs/how_to.md
  go.mod
  go.sum
  openapi/headers.go
  openapi/openapi_client.go
  openapi/openapi_client_test.go
  openapi/openapi_spec_authenticator_api_test.go
  openapi/openapi_spec_authenticator_apikey.go
  openapi/openapi_spec_authenticator_apikey_test.go
  openapi/openapi_spec_authenticator_refresh_token.go
  openapi/openapi_spec_authenticator_refresh_token_test.go
  openapi/openapi_spec_security_definition_apikey_header_bearer.go
  openapi/openapi_spec_security_definition_apikey_header_bearer_test.go
  openapi/openapi_spec_security_definition_apikey_header_test.go
  openapi/openapi_spec_security_definition_apikey_query_test.go
  openapi/openapi_spec_security_definition_apikey_refresh_token.go
  openapi/openapi_spec_security_definition_apikey_refresh_token_test.go
  openapi/openapi_spec_security_definition_spec_apikey.go
  openapi/openapi_spec_security_definitions.go
  openapi/openapi_spec_security_definitions_test.go
  openapi/openapi_v2_security.go
  openapi/openapi_v2_security_test.go
  openapi/provider_factory_test.go
  openapi/utils.go
  openapi/utils_test.go
  tests/e2e/gray_box_plugin_test.go
Labels: feature request

#165 Feature/use terraform plugin sdk
  examples/goa/api/bottle.go
  examples/goa/api/design/design.go
  examples/swaggercodegen/api/api/auth.go
  examples/swaggercodegen/api/api/content_delivery_network_v1_array_of_objects_example.go
  go.mod
  go.sum
  main.go
  openapi/common.go
  openapi/common_test.go
  openapi/data_source_factory.go
  openapi/data_source_factory_test.go
  openapi/data_source_instance_factory.go
  openapi/data_source_instance_factory_test.go
  openapi/openapi_spec_resource_schema_definition.go
  openapi/openapi_spec_resource_schema_definition_property.go
  openapi/openapi_spec_resource_schema_definition_property_test.go
  openapi/openapi_spec_resource_schema_definition_test.go
  openapi/provider.go
  openapi/provider_configuration.go
  openapi/provider_configuration_endpoints.go
  openapi/provider_configuration_endpoints_test.go
  openapi/provider_factory.go
  openapi/provider_test.go
  openapi/resource_factory.go
  openapi/resource_factory_test.go
  openapi/terraformutils/terraform_utils.go
  openapi/terraformutils/terraform_utils_test.go
  openapi/test_utils.go
  tests/e2e/gray_box_cdns_test.go
  tests/e2e/gray_box_plugin_test.go
  tests/e2e/test_api_utils.go
  tests/integration/int_utils_test.go
  tests/integration/provider_plugin_configuration_test.go
  tests/integration/provider_test.go
  tests/integration/resource_cdns_test.go
  tests/integration/resource_lbs_test.go
  tests/integration/resource_monitors_test.go
Labels: feature request, tech-debt

#166 Making repo awesome
  README.md
Labels: enhancement

#167 push code cov report from ci build too
  .gitignore
  .travis.yml
  Makefile
Labels: enhancement

#168 Fix goreportcard issues
  Makefile
  main.go
  openapi/common.go
  openapi/common_test.go
  openapi/data_source_instance_factory_test.go
  openapi/openapi_client_test.go
  openapi/openapi_spec_authenticator_apikey_header_test.go
  openapi/openapi_spec_resource_schema_definition_test.go
  openapi/openapi_spec_security_definition_apikey_header_bearer_test.go
  openapi/openapi_spec_security_schemes_test.go
  openapi/openapi_v2_backend_configuration_test.go
  openapi/openapi_v2_resource_test.go
  openapi/openapi_v2_spec_analyser.go
  openapi/openapi_v2_spec_analyser_test.go
  openapi/openapiutils/openapi_utils.go
  openapi/plugin_config_schema_test.go
  openapi/plugin_config_services_test.go
  openapi/plugin_config_test.go
  openapi/provider_configuration_endpoints_test.go
  openapi/provider_configuration_test.go
  openapi/provider_factory.go
  openapi/provider_test.go
  openapi/resource_factory_test.go
  tests/e2e/test_api_utils.go
  tests/integration/int_utils_test.go
Labels: enhancement

#173 support provider name with version containing multiple digits (e,g: terraform-provider-openapi_v0.20.0)
  main.go
  main_test.go
Labels: bug

#170 fix IneffAssign issues
  openapi/data_source_factory.go
  openapi/data_source_factory_test.go
  openapi/openapi_spec_resource_schema_definition.go
Labels: enhancement

#174 Remove error out when API returns properties that are not specified in the resource definition model
  go.mod
  openapi/common.go
  openapi/common_test.go
  openapi/resource_factory.go
  openapi/resource_factory_test.go
  tests/integration/resource_cdns_test.go
Labels: bug

#175 Feature/post opeartion with no inputs
  docs/how_to.md
  go.mod
  go.sum
  openapi/openapi_v2_spec_analyser.go
  openapi/openapi_v2_spec_analyser_test.go
  tests/e2e/resources_test.go
Labels: feature request

#177 Bugfix/duplicate resources
  go.mod
  go.sum
  openapi/openapi_v2_spec_analyser.go
  openapi/openapi_v2_spec_analyser_test.go
  openapi/provider_configuration.go
  openapi/provider_configuration_endpoints.go
  openapi/provider_configuration_endpoints_test.go
  openapi/provider_configuration_test.go
  openapi/provider_factory.go
  openapi/provider_factory_test.go
  openapi/provider_test.go
Labels: bug
