Repository dikhan/terraform-provider-openapi, pull requests merged in 2019-05, with the labels that each got.

#102 Feature/fix issues using go1.12.4
  .travis.yml
  Gopkg.lock
  README.md
  vendor/github.com/jtolds/gls/stack_tags.go
Labels: bug, enhancement

#105 fix ldgflags to use the new version package instead to bind the stati…
  .goreleaser.yml
Labels: bug

#107 Feature/computed optional props
  build/docker-compose.yml
  docs/faq.md
  docs/how_to.md
  examples/swaggercodegen/api/api/cdn.go
  examples/swaggercodegen/api/api/content_delivery_network.go
  examples/swaggercodegen/api/resources/swagger.yaml
  examples/swaggercodegen/main.tf
  openapi/openapi_spec_resource_schema_definition_property.go
  openapi/openapi_spec_resource_schema_definition_property_test.go
  openapi/openapi_v2_resource.go
  openapi/openapi_v2_resource_test.go
  openapi/provider_factory_test.go
  openapi/resource_factory.go
  openapi/resource_factory_test.go
  openapi/test_utils.go
  tests/integration/resource_cdns_test.go
Labels: feature request

#113 pumping version to 0.13.0
  version
Labels: new version

#116 Feature/upgrade to terraform sdk 0.12
  README.md
  examples/swaggercodegen/main.tf
  go.mod
  go.sum
  openapi/resource_factory.go
  openapi/resource_factory_test.go
  tests/integration/resource_cdns_test.go
  tests/integration/resource_monitors_test.go
Labels: breaking-change

#117 Update docs to reflect go version dependency change to 1.12.4
  docs/release.md
  examples/goa/README.md
Labels: bug

#121 Feature/upgrade example configs to 0.12upgrade
  README.md
  docs/terraform_version_upgrades/upgrading_to_terraform_0.12.md
  examples/swaggercodegen/main.tf
  examples/swaggercodegen/versions.tf
Labels: bug

#123 Feature/update to 0.12.0 not rc
  Dockerfile
  README.md
  go.mod
  go.sum
Labels: bug
