Repository dikhan/terraform-provider-openapi, pull requests merged in 2020-04, with the labels that each got.

#210 [FeatureRequest: Issue #209] Add telemetry http endpoint support
  .travis.yml
  Makefile
  docs/plugin_configuration_schema.md
  go.mod
  go.sum
  openapi/headers.go
  openapi/openapi_client_test.go
  openapi/plugin_config_schema.go
  openapi/plugin_config_schema_test.go
  openapi/plugin_config_telemetry.go
  openapi/plugin_config_telemetry_handler_test.go
  openapi/plugin_config_telemetry_provider_graphite.go
  openapi/plugin_config_telemetry_provider_graphite_test.go
  openapi/plugin_config_telemetry_provider_httpendpoint.go
  openapi/plugin_config_telemetry_provider_httpendpoint_test.go
  tests/e2e/provider_plugin_configuration_test.go
  tests/integration/provider_plugin_configuration_test.go
Labels: feature request

#211 [BugFix: Issue #212] Removing extra ')' in Makefile
  Makefile
Labels: bug-fix

#215 [BugFix: Issue #214] Fix `x-terraform-sensitive` description
  docs/how_to.md
Labels: bug-fix

#213 [NewRelease] v0.27.0
  version
Labels: new version

#216 [BugFix: Issue #217] Fix marshal nil pointer caused when marshalling TelemetryProviderHTTPEndpoint
  openapi/plugin_config_schema_test.go
  openapi/plugin_config_telemetry_provider_httpendpoint.go
  openapi/plugin_config_telemetry_provider_httpendpoint_test.go
Labels: bug-fix

#218 [NewRelease] v0.27.1
  version
Labels: new version

#220 [FeatureRequest: Issue #219] Provider plugin submits tags as part of HTTP telemetry provider
  docs/plugin_configuration_schema.md
  openapi/plugin_config.go
  openapi/plugin_config_schema.go
  openapi/plugin_config_schema_test.go
  openapi/plugin_config_services.go
  openapi/plugin_config_services_schema_property_configuration.go
  openapi/plugin_config_services_stub.go
  openapi/plugin_config_services_test.go
  openapi/plugin_config_telemetry.go
  openapi/plugin_config_telemetry_handler.go
  openapi/plugin_config_telemetry_handler_test.go
  openapi/plugin_config_telemetry_provider_graphite.go
  openapi/plugin_config_telemetry_provider_graphite_test.go
  openapi/plugin_config_telemetry_provider_httpendpoint.go
  openapi/plugin_config_telemetry_provider_httpendpoint_test.go
  openapi/plugin_config_telemetry_provider_stub.go
  openapi/plugin_config_test.go
  openapi/provider_configuration.go
  openapi/provider_factory.go
  openapi/provider_factory_test.go
  tests/e2e/provider_plugin_configuration_test.go
Labels: feature request

#222 [FeatureRequest: Issue #221] Plugin submits resource information and operation performed as part of telemetry metrics
  docs/plugin_configuration_schema.md
  examples/swaggercodegen/api/api/http_utils.go
  examples/swaggercodegen/api/api/lb_api.go
  openapi/openapi_client.go
  openapi/openapi_client_stub.go
  openapi/openapi_client_test.go
  openapi/plugin_config_telemetry.go
  openapi/plugin_config_telemetry_handler.go
  openapi/plugin_config_telemetry_handler_stub.go
  openapi/plugin_config_telemetry_handler_test.go
  openapi/plugin_config_telemetry_provider_graphite.go
  openapi/plugin_config_telemetry_provider_graphite_test.go
  openapi/plugin_config_telemetry_provider_httpendpoint.go
  openapi/plugin_config_telemetry_provider_httpendpoint_test.go
  openapi/plugin_config_telemetry_provider_stub.go
  openapi/provider_factory.go
  openapi/provider_factory_test.go
  openapi/resource_factory.go
  openapi/resource_factory_test.go
  tests/e2e/provider_plugin_configuration_test.go
  tests/integration/resource_lbs_test.go
Labels: feature request

#223 [NewRelease] v0.28.0
  version
Labels: new version
