Repository dikhan/terraform-provider-openapi, pull requests merged in 2020-07, with the labels that each got.

#247 [NewRelease] v0.30.0
  version
Labels: new version

#249 [FeatureRequest: Issue #248] Add sections to documentaton generator
  pkg/terraformdocsgenerator/README.md
  pkg/terraformdocsgenerator/example_provider_documentation_output.html
  pkg/terraformdocsgenerator/main.go
  pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_provider_doc_generator.go
  pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_provider_documentation.go
  pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_provider_documentation_data_sources.go
  pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_provider_documentation_resources.go
  pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_provider_documentation_test.go
  pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_template_html.go
  pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_template_html_test.go
  pkg/terraformdocsgenerator/openapiterraformdocsgenerator/utils.go
  pkg/terraformdocsgenerator/openapiterraformdocsgenerator/utils_test.go
Labels: feature request

#251 [TechDebt: Issue #250] Update PR template to include issue closing keyword
  .github/PULL_REQUEST_TEMPLATE.md
Labels: tech-debt

#252 [NewRelease] v0.30.1
  version
Labels: new version

#254 [TechDebt: Issue #253] Add gosec to CI/CD pipeline and address gosec alerts
  .github/CONTRIBUTING.md
  Makefile
  go.mod
  go.sum
  openapi/common.go
  openapi/common_test.go
  openapi/data_source_factory_test.go
  openapi/data_source_instance_factory_test.go
  openapi/helperutils_test.go
  openapi/openapi_stub_resource.go
  openapi/openapi_v2_security.go
  openapi/plugin_config.go
  openapi/plugin_config_services_schema_property_configuration.go
  openapi/plugin_config_services_schema_property_configuration_test.go
  openapi/provider.go
  openapi/resource_factory.go
  openapi/resource_factory_test.go
  openapi/utils.go
  openapi/utils_test.go
  tests/e2e/test_api_utils.go
Labels: tech-debt

#255 [TechDebt: Issue #256] Support description field in array items schema
  openapi/openapi_v2_resource.go
  openapi/openapi_v2_resource_test.go
  pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_provider_doc_generator.go
  pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_provider_doc_generator_test.go
  pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_provider_documentation_properties.go
  pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_template_html.go
  pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_template_html_test.go
Labels: tech-debt

#257 [NewRelease] v0.31.0
  version
Labels: new version

#261 [TechDebt: Issue #260] Plugin execution improvements
  openapi/common.go
  openapi/common_test.go
  openapi/openapi_spec_resource.go
  openapi/openapi_v2_resource.go
  openapi/openapi_v2_resource_test.go
  openapi/resource_factory.go
  openapi/resource_factory_test.go
Labels: enhancement, tech-debt

#262 [NewRelease] v0.31.1
  version
Labels: new version
