Repository dikhan/terraform-provider-openapi, pull requests merged in 2020-05, with the labels that each got.

#225 [FeatureRequest: Issue #224] Add telemetry to data sources
  docs/plugin_configuration_schema.md
  openapi/data_source_factory.go
  openapi/data_source_factory_test.go
  openapi/data_source_instance_factory.go
  openapi/data_source_instance_factory_test.go
  openapi/plugin_config_telemetry_handler.go
  openapi/plugin_config_telemetry_handler_test.go
  openapi/resource_factory.go
  openapi/resource_factory_test.go
  tests/e2e/provider_plugin_configuration_test.go
Labels: feature request

#226 [NewRelease] v0.28.1
  version
Labels: bug-fix, new version

#229 [FeatureRequest: Issue #228] Ignore array prop ordering
  docs/how_to.md
  go.mod
  go.sum
  openapi/common.go
  openapi/common_test.go
  openapi/data_source_factory.go
  openapi/data_source_instance_factory.go
  openapi/openapi_spec_resource_schema_definition_property.go
  openapi/openapi_spec_resource_schema_definition_property_test.go
  openapi/openapi_v2_resource.go
  openapi/openapi_v2_resource_test.go
  tests/e2e/gray_box_cdns_test.go
Labels: feature request

#230 [NewRelease] v0.29.0
  version
Labels: new version

#232 [BugFix: Issue #231 ] Import errors when resource to be imported does not exists
  openapi/resource_factory.go
  openapi/resource_factory_test.go
Labels: bug-fix

#234 Add support for x-ignore-order
  openapi/openapi_v2_resource.go
  openapi/openapi_v2_resource_test.go
Labels: feature request

#235 [NewRelease] v0.29.1
  version
Labels: new version

#237 [BugFix: Issue #236] Don't update the state if the import fails
  openapi/resource_factory.go
  openapi/resource_factory_test.go
Labels: bug-fix

#238 [NewRelease] v0.29.2
  version
Labels: feature request, new version
