Repository dikhan/terraform-provider-openapi, pull requests merged in 2021-07, with the labels that each got.

#295 [FeatureRequest: Issue #100] Add support for POST with request schema only containing inputs (required/optional) and response only containing outputs (computed properties)
  Makefile
  docs/how_to.md
  docs/release.md
  examples/swaggercodegen/api/resources/swagger.yaml
  go.mod
  go.sum
  openapi/openapi_v2_spec_analyser.go
  openapi/openapi_v2_spec_analyser_test.go
  openapi/provider_test.go
  tests/e2e/gray_box_cdns_test.go
  tests/integration/resource_monitors_test.go
Labels: enhancement, feature request

#307 [NewRelease] v2.1.0
  version
Labels: new version

#306 [FeatureRequest: Issue #305] Support colon characters in field names
  .github/CONTRIBUTING.md
  openapi/terraformutils/terraform_utils.go
  openapi/terraformutils/terraform_utils_test.go
Labels: feature request
