Repository dikhan/terraform-provider-openapi, pull requests merged in 2022-04, with the labels that each got.

#333 [BugFix: Issue #335] goreleaser latest version (1.7) introduced breaking changes requiring Go1.18
  .travis.yml
Labels: tech-debt

#336 [BugFix: Issue #334] Fix make test all
  go.mod
  go.sum
  tests/integration/resource_cdns_test.go
Labels: bug-fix

#337 [BugFix: Issue #X] Skip docker login from forks
  .travis.yml
Labels: bug-fix

#339 [BugFix: Issue #338] Skip docker login from forks
  Makefile
Labels: bug-fix

#332 [FeatureRequest: Issue #329] Adding ARM64 Support
  .goreleaser.yml
Labels: feature request

#340 [NewRelease] v3.0.0
  version
Labels: new version, breaking-change

#341 Fix release pipeline: Only install the binary and not add it to the mod deps
  Makefile
Labels: bug-fix

#342 Major version update v3
  .goreleaser.yml
  Makefile
  docs/major_version_release_notes/openapi_terraform_provider_v3.0.0.md
  docs/publishing_provider.md
  go.mod
  main.go
  openapi/common.go
  openapi/common_test.go
  openapi/openapi_client.go
  openapi/openapi_spec_header.go
  openapi/openapi_spec_resource_schema_definition_property.go
  openapi/openapi_spec_security_definition_apikey_header.go
  openapi/openapi_spec_security_definition_apikey_header_bearer.go
  openapi/openapi_spec_security_definition_apikey_query.go
  openapi/openapi_spec_security_definition_apikey_query_bearer.go
  openapi/openapi_spec_security_definition_apikey_refresh_token.go
  openapi/openapi_spec_security_schemes.go
  openapi/openapi_stub_backend_configuration.go
  openapi/openapi_v2_backend_configuration.go
  openapi/openapi_v2_resource.go
  openapi/plugin_config.go
  openapi/plugin_config_telemetry_provider_httpendpoint.go
  openapi/provider_configuration_endpoints.go
  openapi/provider_factory.go
  openapi/provider_factory_test.go
  openapi/resource_factory.go
  openapi/resource_factory_test.go
  pkg/terraformdocsgenerator/example_provider_documentation_output.html
  pkg/terraformdocsgenerator/main.go
  pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_provider_doc_generator.go
  pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_provider_doc_generator_stubs.go
  pkg/terraformdocsgenerator/openapiterraformdocsgenerator/openapi_terraform_provider_doc_generator_test.go
  tests/e2e/gray_box_cdns_test.go
  tests/e2e/gray_box_plugin_test.go
  tests/e2e/provider_plugin_configuration_test.go
  tests/e2e/resources_test.go
  tests/integration/int_utils_test.go
  tests/integration/provider_plugin_configuration_test.go
  tests/integration/provider_test.go
Labels: breaking-change

#344 [TechDebt: Issue #343] Integrate Go v1.17
  .travis.yml
  README.md
  docs/major_version_release_notes/openapi_terraform_provider_v3.0.0.md
  docs/publishing_provider.md
  go.mod
  go.sum
Labels: tech-debt
